name: test

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: Format
      run: |
        result=$(gofmt -l . | wc -l)
        if [ $result -ne 0 ]; then
          exit 1
        fi

    - name: Vet
      run: go vet -v ./...

    - name: Test
      run: go test -v ./...

